sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
sculpin_theme:
  theme: memtech/memtech-sculpin
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }